name: Deploy to Juno

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24  # Z Juno docs

      - name: Install Dependencies
        run: npm ci  # Stáhne z package.json

      - name: Build
        run: npm run build  # Vytvoří build/

      - name: Deploy to Juno
        uses: junobuild/juno-action@main  # @main – opraví resolve error
        with:
          args: deploy  # Použije config pro hosting z build/
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}  # Tvůj token
